version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "8087:8087"
    environment:
      - FLASK_RUN_PORT=8087
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "8088:8088"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
