version: "3"
services:
  csp-angularjs:
    build: images/web
    ports:
      - "8092:8092"
    environment:
      - FLASK_RUN_PORT=8092
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 60M
